spring:
  cloud:
    gcp:
      project-id: <projectID>
  profiles:
    active: default
server:
  port: 8090
project:
  env: default
  gcp:
    credentials: '<account json key>'
  log:
    path: './local-logs'
    archive:
      clean:
        days: 2  
    app:
      rollover: '1'
      size: '10 MB'
      level: 'DEBUG'
    lib:
      rollover: '1'
      size: '10 MB'
      level: 'INFO'
management:
  security:
    enabled: false
  health:
    jms:
      enabled: false
    rabbit:
      enabled: false
